export const USER_FETCH_DATA = "USER_FETCH_DATA";
export const DELETE_FETCH_DATA = "DELETE_FETCH_DATA";

export const SAVE_USER_DATA = "SAVE_USER_DATA";
export const SAVE_USER_ERROR = "SAVE_USER_ERROR";

export const LOGIN_USER_DATA = "LOGIN_USER_DATA";
export const LOGIN_FORM_DATA = "LOGIN_FORM_DATA";

export const LOGIN_SIGN_INFO = "LOGIN_SIGN_INFO";
export const LOGIN_SIGN_ERROR = "LOGIN_SIGN_ERROR";

export const UPDATE_USER_FORM = "UPDATE_USER_FORM";

export const LOGIN_SAVE_FORM_ERROR = "LOGIN_SAVE_FORM_ERROR";
